packages:
  - "packages/*"
overrides:
  ws: 8.21.3
allowBuilds:
  bufferutil: true
  esbuild: true
  keccak: true
  secp256k1: true
  tiny-secp256k1: true
  unrs-resolver: true
  utf-8-validate: true
  workerd: true
