name = "sortecerta"
compatibility_date = "2026-09-24"
main = "worker.ts"
workers_dev = true
preview_urls = true

[assets]
binding = "ASSETS"
directory = "out"

[vars]
NEXT_PUBLIC_CHAIN_ID = "11155111"
NEXT_PUBLIC_CONFIDENTIAL_PRIZE_POOL_ADDRESS = "0x9c23E5f7143612dc1232FC643A57300291e0d719"
NEXT_PUBLIC_CONFIDENTIAL_USDC_ADDRESS = "0x3B4F71c77e288d92871Cda495891Cd42f543A3f5"
NEXT_PUBLIC_RPC_URL = "https://ethereum-sepolia-rpc.publicnode.com"
NEXT_PUBLIC_USDC_ADDRESS = "0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238"

[[d1_databases]]
binding = "DB"
database_name = "sortecerta-landing"
database_id = "f6f8c304-fa39-495d-8307-d01f3899968a"
migrations_dir = "../landing/migrations"

[previews]

[previews.vars]
NEXT_PUBLIC_CHAIN_ID = "11155111"
NEXT_PUBLIC_CONFIDENTIAL_PRIZE_POOL_ADDRESS = "0x9c23E5f7143612dc1232FC643A57300291e0d719"
NEXT_PUBLIC_CONFIDENTIAL_USDC_ADDRESS = "0x3B4F71c77e288d92871Cda495891Cd42f543A3f5"
NEXT_PUBLIC_RPC_URL = "https://ethereum-sepolia-rpc.publicnode.com"
NEXT_PUBLIC_USDC_ADDRESS = "0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238"

[[previews.d1_databases]]
binding = "DB"
database_name = "sortecerta-landing"
database_id = "f6f8c304-fa39-495d-8307-d01f3899968a"
migrations_dir = "../landing/migrations"
